### ISSUE TITLE
BUG: Return non-allocating function

### ISSUE THREAD

**Issue by albop** [EconForge/Dolang.jl#36]
Here is a behaviour which was broken by the last set of changes.
In Dyno we do the following naive thing (with Calculus.jl I haven't tried with SymEngine),
```
ff = FunctionFactory(...., funname=:f_s)
code = make_function(ff)
f_static = eval(code)
```
and then use f_static directly as a non-allocating function (like `f_static(x0,p)`).

Now if I understand correctly the last function defined in the generated code is a non-allocating one, so the the function which is returned by eval is actually `:f_s!`.

**Comment by sglyon** [comment]
Ahh, yes this is true. The last thing returned is indeed `f_s!`

I can make the return be whatever you prefer. 

I think there are three options:

- `f_s`
- `f_s!`
- `(f_s. f_s!)`

which do you prefer?

The first option is the old behavior, but it might even make more sense to return the tuple of allocating and non-allocating

**Comment by albop** [comment]
I agree both is perfect
