### ISSUE TITLE
new compiler should support derivatives with Val{i}

### ISSUE THREAD

**Issue by sglyon** [EconForge/Dolang.jl#46]
See https://github.com/EconForge/Dolo.jl/pull/122/commits/1f0394f4538865ffd234ebff83cdb53a39458775

**Comment by albop** [comment]
yes, both `Val{0}` and `(Val{0}, Val{1})`. Will the latter actually work ?
I know there is something special with `Tuple{}`.

**Comment by sglyon** [comment]
Done in #47 

You are right that tuples are special. Instead of doing `(Val{0}, Val{1})` we should instead do the (less ugly IMO) `Val{(0, 1)}`
